name: The Evolving Body
favicon: null
layout_spectrum: 0.14714
typography_spectrum: 0.38772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494949'
    - '#2d2d2d'
    - '#575b40'
    - '#738146'
    - '#67733d'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
